name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - name: Diplodoc build action
        # You may pin to the exact commit or the version.
        # uses: v8tenko/diplodoc-playground@522d167301efcde2ae2e90b3cd3c16f51ea01e57
        uses: v8tenko/diplodoc-playground@v0.2
        with:
          # Path to doc to build
          path: 'hello'
