name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      # - run: bash prepare.bash
      - run: npm i
      - run: npm run build
      - run: npm run start
