name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    permissions: 
      contents: write
    name: Deploy sample docs
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: node 'dist/index.js'
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          target-folder: ${{github.head_ref || github.ref_name}}
          folder: project-output/test
