name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    name: Verify Files
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create env file
        run: |
          touch .env
          echo ENGINE_API_KEY=${{ secrets.ENGINE_API_KEY }} >> .env
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: bash update.bash
      - run: bash prepare.bash
      - run: npm i
      - run: npm run build
      - run: npm run start
