name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    name: Verify Files
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: bash update.bash
      - run: bash prepare.bash
      - run: npm i
      - run: npm run build
      - name: Build doc
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run start
