name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    name: Deploy sample docs
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create env file
        run: |
          touch .env
          echo GH_TOKEN=${{ secrets.GH_TOKEN }} >> .env
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
      - run: npm run start
